version: '3.7'

volumes:
  pg_data:
services:
  pg:
    container_name: pg_saas
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=saas
      - POSTGRESQL_PASSWORD=saas
      - POSTGRESQL_DATABASE=saas